// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
const char DEVICE_LOGIN_NAME[]  = "";
const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password
String hora;
float pressao180;
float umidade11;
CloudTemperatureSensor temperatura180;
int presenca;
void initProperties(){
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(hora, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pressao180, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(umidade11, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperatura180, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(presenca, READ, ON_CHANGE, NULL);
}
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID,PASS);
